sudo: required

services:
  - docker

env:
  matrix:
    - EXAMPLE="simple"
    - EXAMPLE="data-containers"
    - EXAMPLE="drush"

before_script:
  - docker version
  - docker-compose version
  - cd examples/${EXAMPLE}

script:
  - docker-compose config
  # - ./tesh.sh

after_script:
  - docker ps -a
